language: python
sudo: false
cache: false
python:
    - '3.6'

install:
  - pip install -rrequirements-tests.txt

script:
  - coverage erase
  - tox
after_success:
  - coverage combine
  - coveralls
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

notifications:
  email:
    - a.vara.1986@gmail.com
