# Generated by Django 2.0.7 on 2018-07-28 18:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('idpublic', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador público')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpublic', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador público')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('milestone', models.DateTimeField(verbose_name='Fecha y hora del precio en el mercado')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Precio')),
                ('provider', models.CharField(max_length=30)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retes_base', to='rates.Currency', verbose_name='Moneda de referencia')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.Currency', verbose_name='')),
            ],
            options={
                'db_table': 'rates',
            },
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['-milestone'], name='rates_milesto_ffb181_idx'),
        ),
    ]
